name: Access AKS cluster
on:
  workflow_dispatch:
  
permissions:
  id-token: write

jobs:
  job:
    runs-on: ubuntu-latest
    
    steps:
         
    - name: Az CLI login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Get kubeconfig
      run: az aks get-credentials -g ${{ secrets.RESOURCE_GROUP_NAME }} -n ${{ secrets.AKS_NAME }}
        
    - name: Get kubelogin
#      run: brew install Azure/kubelogin/kubelogin
      run: |
            curl -LO "https://github.com/Azure/kubelogin/releases/download/v0.0.30/kubelogin-linux-amd64.zip"
            sudo unzip -j "kubelogin-linux-amd64.zip" -d /usr/local/bin
            rm -f "kubelogin-linux-amd64.zip"
            kubelogin --version
        
    - name: Convert kubeconfig
      run: kubelogin convert-kubeconfig -l workloadidentity
       
       
    - name: Retrieve id-token and store
      run: |
        IDTOKEN=$(curl -sSL -H "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" -H "Accept: application/json; api-version=2.0" -H "Content-Type: application/json" "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=api://AzureADTokenExchange" | jq -r '.value')
        echo $IDTOKEN > ${RUNNER_TEMP}/.token
        echo $IDTOKEN
        
      
    - name: Run kubectl
      env:
        AZURE_AUTHORITY_HOST: https://login.microsoftonline.com/
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: |
        export AZURE_FEDERATED_TOKEN_FILE=${RUNNER_TEMP}/.token
        echo $AZURE_FEDERATED_TOKEN_FILE
        kubectl get nodes
        # kubectl apply -f deployment.yaml
        
      
